---
title: Viash project template
format: gfm
engine: knitr
toc: false
---

<!-- README.md is generated from README.qmd using quarto render. Please edit that file -->

This repository is a template for setting up a new [Viash](https://viash.io) project. Follow the ["Quickstart"](https://viash.io/quickstart/) tutorial to learn how to get started with this repository.

## Documentation

The Viash documentation is available online at [`viash.io`](https://viash.io).

## License

Copyright (C) 2020 Data Intuitive

This program is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or (at your
option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
Public License for more details.

You should have received a copy of the GNU General Public License along
with this program. If not, see <http://www.gnu.org/licenses/>.
