name: viash test CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

# Skip older CI runs for pull requests (head_ref exists), otherwise always build
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency: 
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # phase 1
  list_components:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
    - uses: actions/checkout@v3

    - uses: viash-io/viash-actions/setup@v1.0.0

    - id: set_matrix
      run: |
        echo "::set-output name=matrix::$( viash ns list -p docker --format json | jq -c '[ .[] | .info.config ]' )"

    outputs:
        matrix: ${{ steps.set_matrix.outputs.matrix }}

  # phase 2
  viash_test:
    needs: list_components

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      fail-fast: false
      matrix:
        component_path: ${{ fromJson(needs.list_components.outputs.matrix) }}

    steps:
    - uses: actions/checkout@v3

    - uses: viash-io/viash-actions/setup@v1.0.0

    - name: Run test
      run: |
        viash test -p docker ${{ matrix.component_path }}

